Link with GTK libraries
Otherwise the link fails with:

    build/release/tmwxGUI/tmwxOptimizerDialog/tmwxOptimizerDialog_gtk.o:
      undefined reference to symbol 'gtk_window_set_transient_for'
    .../libgtk-3.so.0: error adding symbols: DSO missing from command line